repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: tests/.*\.sol
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
        exclude: tests/.*\.sol
      - id: trailing-whitespace
        exclude: tests/.*\.sol
  - repo: local
    hooks:
      - id: cargo_check
        name: cargo check
        entry: cargo check
        language: system
        pass_filenames: false
        types: [ rust ]
      - id: cargo_fmt
        name: cargo fmt
        entry: cargo fmt
        args: ["--"]
        language: system
        types: [ rust ]
      - id: cargo_clippy
        name: cargo clippy
        entry: cargo clippy
        args: [ "--", "-D", "warnings" ]
        language: system
        pass_filenames: false
        types: [ rust ]
