name: test-and-release
on: [push]
jobs:
  semantic_release:
    name: semantic release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
          target: x86_64-unknown-linux-gnu
      - name: Run tests
        run: cargo test -- --nocapture
#      - name: Install semantic-release and toml-cli
#        run: |
#          npm install --save-dev \
#            semantic-release \
#            @semantic-release/changelog \
#            @semantic-release/exec \
#            @semantic-release/git \
#              && pip3 install toml-cli
#      - name: Release
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        run: npx semantic-release
