name: test-build-release
on:
  push:
    branches:
      - main
jobs:
  test_build_release:
    name: Test build release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          target: x86_64-unknown-linux-musl
          toolchain: stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target=x86_64-unknown-linux-musl
          use-cross: true
      - name: Build Linux x86_64 release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-musl
          use-cross: true
      - name: Install semantic-release and toml-cli
        run: |
          npm install --save-dev \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
              && pip3 install toml-cli
      - name: Release it!
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
